### ISSUE TITLE
The `ids` query parameter value [-xxxx] is not valid

### ISSUE THREAD

**Issue by HarryWu-CHN** [MuMiN-dataset/mumin-build#12]
Thank you for your wonderful work! 
It worked well on Colab but when I want to run the same code on my laptop, it keep showing 400 "The `ids` query parameter value [-xxxx] is not valid".

I guess that the `id` shouldn't be negative, but why many ids is negative?

![image](https://user-images.githubusercontent.com/63134210/178960620-b6600d37-8c43-4232-bd6a-9c9e131d4bdd.png)

the mumin-large dataset
win10
python3.8.10

**Comment by saattrupdan** [comment]
@HarryWu-CHN 
Can you try to install the development version of the package via `pip install git+https://github.com/MuMiN-dataset/mumin-build@dev` and see if the problem persists? I cannot recreate the error you're getting with the negative tweet IDs, but I'm just forcing all tweet IDs to be positive now.

**Comment by HarryWu-CHN** [comment]
@saattrupdan 
I tried to forcing all tweet IDs to be positive, but encountered the following error.
```
Traceback (most recent call last):
  File ".\MuMiN_start.py", line 38, in <module>
    dataset.compile()
  File "D:\Program Files\Python\Python38\lib\site-packages\mumin\dataset.py", line 253, in compile
    self._rehydrate(node_type='tweet')
  File "D:\Program Files\Python\Python38\lib\site-packages\mumin\dataset.py", line 539, in _rehydrate
    source_tweet_dfs = self._twitter.rehydrate_tweets(**params)
  File "D:\Program Files\Python\Python38\lib\site-packages\mumin\twitter.py", line 212, in rehydrate_tweets
    user_df = (pd.concat((user_df, df))
  File "D:\Program Files\Python\Python38\lib\site-packages\pandas\core\generic.py", line 5799, in astype
    col.astype(dtype=dtype[col_name], copy=copy, errors=errors)
  File "D:\Program Files\Python\Python38\lib\site-packages\pandas\core\generic.py", line 5815, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
  File "D:\Program Files\Python\Python38\lib\site-packages\pandas\core\internals\managers.py", line 418, in astype
    return self.apply("astype", dtype=dtype, copy=copy, errors=errors)
  File "D:\Program Files\Python\Python38\lib\site-packages\pandas\core\internals\managers.py", line 327, in apply
    applied = getattr(b, f)(**kwargs)
  File "D:\Program Files\Python\Python38\lib\site-packages\pandas\core\internals\blocks.py", line 591, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
  File "D:\Program Files\Python\Python38\lib\site-packages\pandas\core\dtypes\cast.py", line 1309, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
  File "D:\Program Files\Python\Python38\lib\site-packages\pandas\core\dtypes\cast.py", line 1257, in astype_array
    values = astype_nansafe(values, dtype, copy=copy)
  File "D:\Program Files\Python\Python38\lib\site-packages\pandas\core\dtypes\cast.py", line 1174, in astype_nansafe
    return lib.astype_intsafe(arr, dtype)
  File "pandas\_libs\lib.pyx", line 679, in pandas._libs.lib.astype_intsafe
OverflowError: Python int too large to convert to C long
```

**Comment by saattrupdan** [comment]
@HarryWu-CHN Aha! Can you please tell me what your output of `python3 -c "import sys; print(sys.maxsize)"` is?

**Comment by saattrupdan** [comment]
@HarryWu-CHN  Alright, thanks. It seems like Windows defaults the `int` type to int32. I've changed the `astype(int)` type casts to int64 now. Could you try re-installing the development version using the same command as above, and see if that fixed it?

**Comment by HarryWu-CHN** [comment]
Does it work well on Linux? I'm thinking about switching to another OS.

**Comment by saattrupdan** [comment]
@HarryWu-CHN
Yeah this seems to be a Windows issue (both MacOS and Linux distros should be fine). 

Can you try deleting your locally compiled dataset (e.g., `mumin-large.zip`), reinstall the development version (`pip install git+https://github.com/MuMiN-dataset/mumin-build@dev`) and try again?

**Comment by saattrupdan** [comment]
@HarryWu-CHN Also, since you said you manually ensure that the integers are not negative, remove that bit of your code please 🙂

**Comment by HarryWu-CHN** [comment]
Still not working😭. I think it might be more efficient for you to find a Windows computer to debug😂

**Comment by HarryWu-CHN** [comment]
@saattrupdan 
Now it can rehydrating tweet nodes and reply nodes. But when the two rehydrating was done, it crashed without any error message, and the dataset was **not** complied.

**Comment by saattrupdan** [comment]
@HarryWu-CHN Yeah I fixed the tweet ID error, but now Windows can fetch neither articles nor images, so I'm trying to fix that. Windows being Windows!

**Comment by saattrupdan** [comment]
@HarryWu-CHN My Windows tests are working now, after I found another Windows culprit (the use of signals in the `timeout-decorator` package). Can you check if things are working on your side now, if you re-install the development version as before?

**Comment by HarryWu-CHN** [comment]
@saattrupdan 
Can compiling "large" datasets run successfully in your windows? As you know, compiling large Mumindataset is so time-consuming😭

**Comment by saattrupdan** [comment]
@HarryWu-CHN I've only tried compiling the small one on Windows, which works. And yes, compiling the large one is time-consuming, it's a lot of data! You could consider compiling the small or medium one, or removing some of the data which you might not need (you can for instance remove replies and/or articles and/or images with `include_replies=False`, `include_articles=False` and/or `include_tweet_images=False`).

**Comment by saattrupdan** [comment]
Fixed in https://github.com/MuMiN-dataset/mumin-build/releases/tag/v1.9.0, closing. Please open a new issue if the problem (or others) persist 🙂
