### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe when parsing images

### ISSUE THREAD

**Issue by HarryWu-CHN** [MuMiN-dataset/mumin-build#14]
The error occurred when the parsing images was around 60-70 percent.

<details><summary>Error Message</summary>
<p>

```
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/usr/local/lib/python3.8/multiprocessing/queues.py", line 368, in put
    self._writer.send_bytes(obj)
  File "/usr/local/lib/python3.8/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/local/lib/python3.8/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header)
  File "/usr/local/lib/python3.8/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
```

</p>
</details>

+ Ubuntu 18.04
+ Python 3.8.10
+ RAM 8GB
+ 4-core CPU

**Comment by HarryWu-CHN** [comment]
This process also has problem on my Windows. All RAM and CPU are occupied, causing the computer to stall.

+ Windows10
+ Python 3.8.10
+ RAM 16GB
+ 8-corn CPU

**Comment by saattrupdan** [comment]
Thanks for all the great feedback @HarryWu-CHN, and I'm sorry that you keep experiencing issues! 

This one seems like you're running out of memory on both of your machines. I could hopefully fix this by storing the image arrays more efficiently, as well as adding a "workers" argument which you could use to decrease the amount of images processed at the same time. 

I'm on holiday right now, so I won't be able to look at it until Monday I'm afraid. 

If you really need it beforehand, then you could fork the repo and change the `mp.cpu_count() - 1` occurrences with `1` in the `data_extraction` module - then you'll at least only be processing one image at a time.

**Comment by saattrupdan** [comment]
@HarryWu-CHN This should be fixed in https://github.com/MuMiN-dataset/mumin-build/releases/tag/v1.10.0 now. More specifically, the images should now take up less memory, and you can now set `chunksize` and `n_jobs` arguments in `MuminDataset` (set both to 1 if you want to use as little memory as possible).
