### ISSUE TITLE
User Posted Reply rows not found

### ISSUE THREAD

**Issue by Luke-Prometheus** [MuMiN-dataset/mumin-build#15]
I have been working with a downloaded version of the Mumin Medium dataset to try and retrieve user information based on replies they have made.
I keep trying to retrieve a User's Row ID via the 'user_reply_to_tweet' relationship dataset and there is no corresponding index for some users.

**For example:**

In the (reply, reply_to, tweet) relationship dataset the fifth src value is 406564.
I then try to retrieve the User's Row ID via the (user, posted, reply) relationship dataset using 406564 as the tgt value.
The row cannot be found, upon closer inspection the dataset ends with the highest row value being 406562.

I then looked into this further and have found 7201 rows failing to connect a reply to a user.
Any help you can give in resolving this would be great. Is this a result of users removing their accounts?

**I have attached the code I have used below:**

    bearer_token = ""
    dataset = MuminDataset(
        twitter_bearer_token="",
        size="medium",
        include_replies=True,
        include_articles=False,
        include_hashtags=False,
        dataset_path="mumin-medium.zip",
        include_tweet_images=False,
        include_extra_images=False
    )

    # Compile
    dataset.compile()

    # Get all the users
    users_list = dataset.nodes["user"]

    # Get the reply and tweet rel connection values
    reply_reply_to_tweet = dataset.rels[('reply', 'reply_to', 'tweet')]
    reply_reply_to_tweet.columns = ["rrt_" + c for c in list(reply_reply_to_tweet.columns)]

    # Get the user posted reply rel connection values
    user_posted_reply = dataset.rels[('user', 'posted', 'reply')]
    user_posted_reply.columns = ["upr_" + c for c in list(user_posted_reply.columns)]

    # Join both relational datasets to retrieve the user rows for each reply
    merged_dataset = pd.merge(reply_reply_to_tweet, user_posted_reply, how="outer", left_on=["rrt_src"], right_on=["upr_tgt"])

    # Locate rows with no connection
    merged_dataset_only_NaN = merged_dataset.loc[merged_dataset["upr_tgt"].isnull()]

    print(merged_dataset)
    print(merged_dataset_only_NaN)

**Comment by saattrupdan** [comment]
Hi @Luke-Prometheus and thanks for the feedback!

My guess would be that they are deleted accounts, yes. But just to make sure that's actually the case, can you post a handful of the user IDs which are not appearing in the (User)-[POSTED]->(Reply) relation? The IDs in the relation dataframe are the indices of the node dataframe.

**Comment by rymc** [comment]
Hi Luke!

Thanks for the code demonstrating the issue, it made it quicker to investigate.

It looks like the reply tweets in `merged_dataset_only_NaN ` are not available.  If you merge that dataframe with the reply dataframe:

`pd.merge(merged_dataset_only_NaN, dataset.nodes['reply'], left_on='rrt_src', right_index=True` 

you will see that none of the resulting ‘text’ column values have any text, and all of the ‘created_at’ column values are NaT. This indicates that we were unable to retrieve those tweets (and thus those users).

If you manually look up those tweet IDs on twitter.com you will see a variety of reasons given as to why they’re unavailable (e.g., user has been suspended, the tweet has been deleted).

I hope that addresses the question (TL;DR those replies are no longer available, and thus we can’t access the user info), but let me know if not.

**Comment by Luke-Prometheus** [comment]
Hi both, thanks for the quick reply.
I've copied a handful of the (reply, reply_to, tweet) src column values that do not match any (user, posted, reply) tgt values.

406564.0, 406565.0, 406571.0, 406573.0, 406576.0, 406577.0, 406578.0, 406579.0, 406580.0, 406581.0, 406591.0, 406592.0, 406593.0, 406594.0, 406595.0, 406596.0, 406597.0, 406598.0, 406599.0, 406600.0

That does explain the issue, i will work around it. I presume the rels file wasn't updated in that case?
Thanks for the support.

**Comment by saattrupdan** [comment]
> That does explain the issue, i will work around it. I presume the rels file wasn't updated in that case? Thanks for the support.

That's right, yes. The POSTED relations are directly extracted from the tweet data, so if the tweets are not available then the scripts won't be able to create them. The REPLY_TO relation is included in the raw downloaded dataset and will thus contain all of the original (reply_id, tweet_id) pairs.

Closing the issue as it seems that your issue has been resolved. If not then please reopen it 🙂
