### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by lujain96** [MuMiN-dataset/mumin-build#18]
Hello,

Thank you for the great effort in this dataset.
I am running the tutorial you provided on Colab and I am trying to compile the dataset but it keeps giving me an SSL error as the following:

`SSLError: HTTPSConnectionPool(host='data.bris.ac.uk', port=443): Max retries exceeded with url: /datasets/23yv276we2mll25fjakkfim2ml/23yv276we2mll25fjakkfim2ml.zip (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1091)')))`

I believe it's because of the URL of the dataset, how can I fix this error?

**Comment by rymc** [comment]
Hi 

It seems like the University of Bristol data server where this was hosted had an expired SSL certificate during that time. It seems they have renewed it now and the URL should work. Sorry about the inconvenience that caused. 

Best wishes
Ryan

**Comment by lujain96** [comment]
Yes it works now, thank you.
