### ISSUE TITLE
The dataset seems not to be at the address now.

### ISSUE THREAD

**Issue by DanniXu98** [MuMiN-dataset/mumin-build#32]
**Hi, I tried to compile the Dataset according to the start-up guidelines.
But It seems the step of download could not work. I got 404 error when download the dataset.**
>>> dataset = MuminDataset(twitter_bearer_token=twitter_bearer_token, size='small')
>>> dataset
MuminDataset(size=small, rehydrated=False, compiled=False, bearer_token_available=True)
>>> dataset.compile()
2024-02-23 08:56:22,985 [INFO] Downloading dataset
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/danni/anaconda3/envs/mumin/lib/python3.8/site-packages/mumin/dataset.py", line 259, in compile
    self._download(overwrite=overwrite)
  File "/home/danni/anaconda3/envs/mumin/lib/python3.8/site-packages/mumin/dataset.py", line 346, in _download
    raise RuntimeError(f"[{response.status_code}] {response.content!r}")
RuntimeError: [404] b'not found'

**Then I tried to open the link "https://data.bris.ac.uk/datasets/23yv276we2mll25f" in dataset.py, line 115 download_url: str = ('https://data.bris.ac.uk/datasets/23yv276we2mll25f' 'jakkfim2ml/23yv276we2mll25fjakkfim2ml.zip')). I also got "not found" from the browser page.**
Could you please help check whether the link address could work? Or give some advice about what can I do to solve this problem?
Thanks!

**Comment by saattrupdan** [comment]
@rymc, do you know about this?

**Comment by rymc** [comment]
[the URL in the code is](https://github.com/MuMiN-dataset/mumin-build/blob/main/src/mumin/dataset.py#L129C4-L132C6) which is  https://data.bris.ac.uk/datasets/23yv276we2mll25fjakkfim2ml/23yv276we2mll25fjakkfim2ml.zip works for me

@saattrupdan is it also working for you?

**Comment by DanniXu98** [comment]
This link (https://data.bris.ac.uk/datasets/23yv276we2mll25fjakkfim2ml/23yv276we2mll25fjakkfim2ml.zip) also works for me. Thanks for your reply!
I am not sure the reason about the "RuntimeError: [404] b'not found'" error. I am doing some checking.

**Comment by DanniXu98** [comment]
It works now! I think it was something wrong about my twitter's bear_token.
Thanks!
