### ISSUE TITLE
Parallel Jobs and checkpoints for dataset compile process

### ISSUE THREAD

**Issue by fablos** [MuMiN-dataset/mumin-build#9]
Hi,
first of all let me say I do like your work very much. The MuMin project is very interesting and well organized. And I have a vague idea about how much effort it might be required to build it.

I started used your scripts to download and compile the dataset and, as you mentioned, setting up all the flags slow down the overall process. Maybe a bunch of parallel processes would help to speed up and Python libraries as multiprocessing and joblib make that not to complicated. 
But, the most urgent change to your code I would like to suggest is some kind of intermediate checkpoint mechanism during the compiling phase. I experienced a technical issue and lost many days of tweet rehydrating. This last feature would be very appreciate.

Thanks again for your work and research.

F

**Comment by saattrupdan** [comment]
Hi @fablos and thanks for your interest in our dataset!

The parallelism won't help much unfortunately, as the vast majority of compilation time is spent merely waiting for the Twitter API, as the usage limits are reached constantly. You can see this during compilation as well, that progress grows steadily and then stops for ~15 minutes, after which it continues again.

The checkpoints could definitely be done, however! I'll put that on my todo list 😊

**Comment by saattrupdan** [comment]
Added a checkpoint after rehydration in https://github.com/MuMiN-dataset/mumin-build/releases/tag/v1.9.0, closing. Please open a new issue if the problem (or others) persist 🙂
